project:
  type: website
  output-dir: docs

website:
  title: "Aaron Case DSPG Blog"
  navbar: 
    background: "#cc0000"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CyberSpeedAC
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

